version: '3.5'

services:
    php:
        build:
            context: ./docker/php
        container_name: "todo-app-php"
        volumes:
            - ./app:/var/www/html
        depends_on:
            - db

    nginx:
        image: nginx:latest
        container_name: "todo-app-nginx"
        volumes:
            - ./docker/nginx/conf.d:/etc/nginx/conf.d
            - ./app:/var/www/html
        ports:
            - "8080:80"
        depends_on:
            - php

    db:
        image: mysql:5.7
        container_name: "todo-app-mysql"
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: todo_app
            MYSQL_USER: user
            MYSQL_PASSWORD: 1234
        volumes:
            - ./docker/db/data:/var/lib/mysql
            #- ./docker/db/init:/docker-entrypoint-initdb.d
        ports:
            - "3306:3306"

    phpmyadmin:
        depends_on:
            - db
        image: phpmyadmin
        restart: always
        ports:
            - "8090:80"
        environment:
            PMA_HOST: db
            MYSQL_ROOT_PASSWORD: root